# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

apiVersion: v1
kind: Namespace
metadata:
  name: jifa-playground
  labels:
    name: jifa-playground

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jifa-playground
  name: jifa
  labels:
    app: jifa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jifa
  template:
    metadata:
      labels:
        app: jifa-master
    spec:
      containers:
        - name: main-container
          image: eclipsejifa/jifa:playground
          imagePullPolicy: Always
          ports:
            - name: jifa-port
              containerPort: 8102

---
apiVersion: v1
kind: Service
metadata:
  namespace: jifa-playground
  name: jifa-service
spec:
  selector:
    app: jifa-master
  ports:
    - protocol: TCP
      port: 80
      targetPort: jifa-port
  type: LoadBalancer
