apiVersion: v1
kind: Service
metadata:
  name: {{ include "jifa.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "jifa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: jifa-port
      protocol: TCP
  selector:
    {{- include "jifa.selectorLabels" . | nindent 4 }}
