apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jifa.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "jifa.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}