#
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v2
name: jifa
description: Eclipse Jifa (abbreviated as Jifa) stands for "Java Issues Finding Assistant". This project originated from an internal system which was designed to improve the efficiency of diagnosing Java heap related issues that occurred in the production environment. It was open sourced and contributed to the Eclipse Foundation in 2020.
type: application
version: 0.3.0
appVersion: 0.3.0-SNAPSHOT