#
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

replicaCount: 1

## @param image.repository jifa master workload image
image:
  repository: eclipsejifa/jifa
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is latest.
  tag: ""

  ## @param worker.repository jifa worker workload image
  worker:
    repository: eclipsejifa/jifa
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is latest.
    tag: ""


persistence:
  ## @param persistence.storageClass PVC Storage Class for jifa data volume
  storageClass: ""
  ## @param persistence.accessModes PVC Access Mode for jifa data volume
  accessModes:
    - ReadWriteMany
  ## @param persistence.size PVC Storage Request for jifa data volume
  size: 3Gi

## Role Based Access Control
## ref: https://kubernetes.io/docs/admin/authorization/rbac/
##
rbac:
  ## @param rbac.create Whether to create & use RBAC resources or not
  ## binding jifa ServiceAccount to a role
  ## that allows jifa pods querying the K8s API
  ##
  create: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


mysql:
  ## @param mysql.create Whether to build Mysql by itself. If set to true, a Mysql instance will be created.
  create: true
  ## @param mysql.host Mysql Host for jifa database
  host: "jifa-mysql:3306"
  database: "jifa"
  user: "root"
  password: "password"

  service:
    type: ClusterIP
    port: 3306

  persistence:
    ## @param persistence.accessModes PVC Access Mode for mysql data volume
    accessModes:
      - ReadWriteOnce
    ## @param persistence.size PVC Storage Request for mysql data volume
    size: 1Gi

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

